/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'updatedAt' : Time,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Cuisine = IDL.Variant({
  'other' : IDL.Text,
  'chinese' : IDL.Null,
  'mexican' : IDL.Null,
  'italian' : IDL.Null,
  'indian' : IDL.Null,
  'american' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'cuisineType' : Cuisine,
  'description' : IDL.Text,
  'updatedAt' : Time,
});
export const UserProfile = IDL.Record({
  'isRestaurantOwner' : IDL.Bool,
  'name' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'sessionId' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'ready' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'createdAt' : Time,
  'restaurantId' : IDL.Nat,
  'updatedAt' : Time,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [MenuItem],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Restaurant],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getMenuItems' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrderStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'totalOrders' : IDL.Nat, 'totalRevenue' : IDL.Nat })],
      ['query'],
    ),
  'getOrdersByRestaurant' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getRestaurant' : IDL.Func([IDL.Nat], [Restaurant], ['query']),
  'getRestaurantsByCuisine' : IDL.Func(
      [Cuisine],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'getRestaurantsByCuisineText' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [Order],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
  'updateMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [MenuItem],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
  'updateRestaurant' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Restaurant],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'updatedAt' : Time,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Cuisine = IDL.Variant({
    'other' : IDL.Text,
    'chinese' : IDL.Null,
    'mexican' : IDL.Null,
    'italian' : IDL.Null,
    'indian' : IDL.Null,
    'american' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'cuisineType' : Cuisine,
    'description' : IDL.Text,
    'updatedAt' : Time,
  });
  const UserProfile = IDL.Record({
    'isRestaurantOwner' : IDL.Bool,
    'name' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'sessionId' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'createdAt' : Time,
    'restaurantId' : IDL.Nat,
    'updatedAt' : Time,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [MenuItem],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Restaurant],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getCustomerOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getMenuItems' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrderStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'totalOrders' : IDL.Nat, 'totalRevenue' : IDL.Nat })],
        ['query'],
      ),
    'getOrdersByRestaurant' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getRestaurant' : IDL.Func([IDL.Nat], [Restaurant], ['query']),
    'getRestaurantsByCuisine' : IDL.Func(
        [Cuisine],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'getRestaurantsByCuisineText' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [Order],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [MenuItem],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
    'updateRestaurant' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Restaurant],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };