/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Cuisine = { 'other' : string } |
  { 'chinese' : null } |
  { 'mexican' : null } |
  { 'italian' : null } |
  { 'indian' : null } |
  { 'american' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'available' : boolean,
  'updatedAt' : Time,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'sessionId' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'createdAt' : Time,
  'restaurantId' : bigint,
  'updatedAt' : Time,
  'customerId' : Principal,
  'items' : Array<[bigint, bigint]>,
  'totalPrice' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'ready' : null };
export interface Restaurant {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'cuisineType' : Cuisine,
  'description' : string,
  'updatedAt' : Time,
}
export type Time = bigint;
export interface UserProfile { 'isRestaurantOwner' : boolean, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    MenuItem
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRestaurant' : ActorMethod<[string, string, string], Restaurant>,
  'deleteMenuItem' : ActorMethod<[bigint, bigint], undefined>,
  'getAllRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[string], Array<Message>>,
  'getCustomerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getMenuItems' : ActorMethod<[bigint], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[bigint, string], Array<MenuItem>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrderStats' : ActorMethod<
    [bigint],
    { 'totalOrders' : bigint, 'totalRevenue' : bigint }
  >,
  'getOrdersByRestaurant' : ActorMethod<[bigint], Array<Order>>,
  'getRestaurant' : ActorMethod<[bigint], Restaurant>,
  'getRestaurantsByCuisine' : ActorMethod<[Cuisine], Array<Restaurant>>,
  'getRestaurantsByCuisineText' : ActorMethod<[string], Array<Restaurant>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[bigint, Array<[bigint, bigint]>], Order>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<[string, string], Message>,
  'updateMenuItem' : ActorMethod<
    [bigint, bigint, string, string, bigint, string, string, boolean],
    MenuItem
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], Order>,
  'updateRestaurant' : ActorMethod<
    [bigint, string, string, string],
    Restaurant
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];