/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    available: boolean;
    updatedAt: Time;
    imageUrl: string;
    category: string;
    price: bigint;
}
export type Time = bigint;
export type Cuisine = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
};
export interface Message {
    id: bigint;
    content: string;
    sender: Principal;
    timestamp: Time;
    sessionId: string;
}
export interface Restaurant {
    id: bigint;
    owner: Principal;
    name: string;
    createdAt: Time;
    cuisineType: Cuisine;
    description: string;
    updatedAt: Time;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    createdAt: Time;
    restaurantId: bigint;
    updatedAt: Time;
    customerId: Principal;
    items: Array<[bigint, bigint]>;
    totalPrice: bigint;
}
export interface UserProfile {
    isRestaurantOwner: boolean;
    name: string;
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed",
    ready = "ready"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMenuItem(restaurantId: bigint, name: string, description: string, price: bigint, category: string, imageUrl: string): Promise<MenuItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createRestaurant(name: string, description: string, cuisineType: string): Promise<Restaurant>;
    deleteMenuItem(restaurantId: bigint, menuItemId: bigint): Promise<void>;
    getAllRestaurants(): Promise<Array<Restaurant>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(sessionId: string): Promise<Array<Message>>;
    getCustomerOrders(customerId: Principal): Promise<Array<Order>>;
    getMenuItems(restaurantId: bigint): Promise<Array<MenuItem>>;
    getMenuItemsByCategory(restaurantId: bigint, category: string): Promise<Array<MenuItem>>;
    getOrder(orderId: bigint): Promise<Order>;
    getOrderStats(restaurantId: bigint): Promise<{
        totalOrders: bigint;
        totalRevenue: bigint;
    }>;
    getOrdersByRestaurant(restaurantId: bigint): Promise<Array<Order>>;
    getRestaurant(restaurantId: bigint): Promise<Restaurant>;
    getRestaurantsByCuisine(cuisineType: Cuisine): Promise<Array<Restaurant>>;
    getRestaurantsByCuisineText(cuisineType: string): Promise<Array<Restaurant>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(restaurantId: bigint, items: Array<[bigint, bigint]>): Promise<Order>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendChatMessage(sessionId: string, content: string): Promise<Message>;
    updateMenuItem(restaurantId: bigint, menuItemId: bigint, name: string, description: string, price: bigint, category: string, imageUrl: string, available: boolean): Promise<MenuItem>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<Order>;
    updateRestaurant(restaurantId: bigint, name: string, description: string, cuisineType: string): Promise<Restaurant>;
}
import type { Cuisine as _Cuisine, Order as _Order, OrderStatus as _OrderStatus, Restaurant as _Restaurant, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createRestaurant(arg0: string, arg1: string, arg2: string): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.createRestaurant(arg0, arg1, arg2);
                return from_candid_Restaurant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRestaurant(arg0, arg1, arg2);
            return from_candid_Restaurant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMenuItem(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0, arg1);
            return result;
        }
    }
    async getAllRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRestaurants();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRestaurants();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getCustomerOrders(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrders(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrders(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItems(arg0: bigint): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems(arg0);
            return result;
        }
    }
    async getMenuItemsByCategory(arg0: bigint, arg1: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0, arg1);
            return result;
        }
    }
    async getOrder(arg0: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStats(arg0: bigint): Promise<{
        totalOrders: bigint;
        totalRevenue: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStats(arg0);
            return result;
        }
    }
    async getOrdersByRestaurant(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByRestaurant(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByRestaurant(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: bigint): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_Restaurant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_Restaurant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantsByCuisine(arg0: Cuisine): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantsByCuisine(to_candid_Cuisine_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantsByCuisine(to_candid_Cuisine_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantsByCuisineText(arg0: string): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantsByCuisineText(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantsByCuisineText(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: bigint, arg1: Array<[bigint, bigint]>): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1);
                return from_candid_Order_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1);
            return from_candid_Order_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: string, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1);
            return result;
        }
    }
    async updateMenuItem(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: boolean): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Order_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Order_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRestaurant(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurant(arg0, arg1, arg2, arg3);
                return from_candid_Restaurant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurant(arg0, arg1, arg2, arg3);
            return from_candid_Restaurant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cuisine_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cuisine): Cuisine {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Restaurant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Restaurant {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    createdAt: _Time;
    restaurantId: bigint;
    updatedAt: _Time;
    customerId: Principal;
    items: Array<[bigint, bigint]>;
    totalPrice: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    createdAt: Time;
    restaurantId: bigint;
    updatedAt: Time;
    customerId: Principal;
    items: Array<[bigint, bigint]>;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n14(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        restaurantId: value.restaurantId,
        updatedAt: value.updatedAt,
        customerId: value.customerId,
        items: value.items,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: Principal;
    name: string;
    createdAt: _Time;
    cuisineType: _Cuisine;
    description: string;
    updatedAt: _Time;
}): {
    id: bigint;
    owner: Principal;
    name: string;
    createdAt: Time;
    cuisineType: Cuisine;
    description: string;
    updatedAt: Time;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        cuisineType: from_candid_Cuisine_n5(_uploadFile, _downloadFile, value.cuisineType),
        description: value.description,
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    ready: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : "ready" in value ? OrderStatus.ready : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    american: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "chinese" in value ? {
        __kind__: "chinese",
        chinese: value.chinese
    } : "mexican" in value ? {
        __kind__: "mexican",
        mexican: value.mexican
    } : "italian" in value ? {
        __kind__: "italian",
        italian: value.italian
    } : "indian" in value ? {
        __kind__: "indian",
        indian: value.indian
    } : "american" in value ? {
        __kind__: "american",
        american: value.american
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Array<Restaurant> {
    return value.map((x)=>from_candid_Restaurant_n3(_uploadFile, _downloadFile, x));
}
function to_candid_Cuisine_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cuisine): _Cuisine {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
}): {
    other: string;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    american: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "chinese" ? {
        chinese: value.chinese
    } : value.__kind__ === "mexican" ? {
        mexican: value.mexican
    } : value.__kind__ === "italian" ? {
        italian: value.italian
    } : value.__kind__ === "indian" ? {
        indian: value.indian
    } : value.__kind__ === "american" ? {
        american: value.american
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    ready: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value == OrderStatus.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
